src/SATI.BackOffice.Site/Controllers/IndisponibilidadSitioController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SATI.BackOffice.Site.Controllers
{
    public class IndisponibilidadSitioController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/SATI.BackOffice.Site/Views/Shared/Mensaje.cshtml
<!-- Modal -->
<div class="modal fade" id="msjModal" tabindex="-1" role="dialog" aria-labelledby="msjTitulo" data-keyboard="false" data-backdrop="static" aria-hidden="true" style="z-index: 999999;" >
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div id="msjHeader" class="modal-header">
                <span id="msjIcono" class="" style="margin-top: -2px; margin-right: 5px;"></span>
                <h5 id="msjTitulo">¡Atención!</h5>
                <button type="button" class="close" onclick="AceptarMensaje('NO');" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div id="msjContenido" class="modal-body">
            </div>
            <div class="modal-footer">
                <button id="btnMensajeAceptar" type="button" class="btn btn-primary">Aceptar</button>
                <button id="btnMensajeCancelar" type="button" class="btn btn-secondary" data-dismiss="modal" onclick="CerrarMensaje('NO');">Cancelar</button>
            </div>
        </div>
    </div>
</div>

<script>
    $("#btnMensajeAceptar").click(function (evento) {
        AceptarMensaje('SI');
        evento.preventDefault();
        evento.stopPropagation();

        return false;
    });

</script>

src/SATI.BackOffice.Site/Views/Shared/Waiting.cshtml
<div id="wWaiting" class="modal fade in" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="false" style="display: none; background-color: whitesmoke; opacity: .8 !important; z-index: 199099 !Important">
    <div class="modal-body" style="position: absolute;
        left: 50%;
        top: 50%;
        transform: translate(-50%, -50%);
        -webkit-transform: translate(-50%, -50%);
        text-align: center;
        color: brown;">
        <img src="@Url.Content("~/Logos/Logo Gobierno-DGR.png")" alt="Cargando..." style="zoom: 1;">
        <div style="text-align: center;">
            <i class="fas fa-3x fa-spin fa-spinner"></i>
        </div>
        <div style="text-align: center;">
            <label id="lblWaiting">Procesando... Espere un momento por favor.</label>
        </div>
    </div>
</div>

src/SATI.BackOffice.Site/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--Meta no Cache-->
    <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate">
    <meta http-equiv="Pragma" content="no-cache">
    <meta http-equiv="Expires" content="0">

    <title>@ViewData["Title"] - BackOffice - DGR Web</title>

    <link href="~/EstiloGobierno/css/custom-bootstrap.min.css" rel="stylesheet" />
    <link href="~/EstiloGobierno/css/patron.css" rel="stylesheet" />
    <link href="~/EstiloGobierno/css/patron-iconos.css" rel="stylesheet" />
    <link href="~/fontawesome/css/all.css" rel="stylesheet" />
    <link href="~/flickity.css" rel="stylesheet" />
    <link href="~/bootstrap/select2/dist/css/select2.min.css" rel="stylesheet" />
    <link href="~/bootstrap-datepicker/css/bootstrap-datepicker.min.css" rel="stylesheet" />
    <link href="~/bootstrap/gritter/css/jquery.gritter.css" rel="stylesheet" />
    <link href="~/css/float.css" rel="stylesheet" />

    <script src="~/js/modernizr-2.8.3.js"></script>
</head>
<body>
    <header>
        <!-- SECCION NAVEGACIÓN-->
        <nav class="navbar navbar-light navbar-expand-md" id="navbar-ppal">
            <div class="container">
                <a href="http://www.sanjuan.gob.ar" class="navbar-brand padre-img1">
                    <img src="~/EstiloGobierno/img/logo.png" alt="Isologo Gobierno de San Juan" width="150">
                </a>
                <a href="https://rentas.sanjuan.gob.ar" class="navbar-brand padre-img2">
                    <img src="@(Url.Content("~/EstiloGobierno/img/rentas/rentas-hacienda-cabecera.png"))" alt="Isologo Rentas de San Juan" width="150" class="img2">
                </a>
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#menu-principal"
                        aria-controls="menu-principal" aria-expanded="false" aria-label="Desplegar menú de navegación">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @*<div class="collapse navbar-collapse" id="menu-principal">
                    <partial name="Sesion" />
                </div>*@
            </div>
        </nav>
    </header>
    <div class="container">
        <!-- begin scroll to top btn -->
        <a href="javascript:void(0);" class="btn-scroll-to-top btn btn-secondary" title="Subir" style="display: none;">Top<span></span></a>
        <!-- end scroll to top btn  fa-angle-up-->
        @RenderBody()

        <footer class="container-fluid bg-primary py-5">
            <div class="container">
                <div class="row">
                    <div class="col-12 col-md-3 mb-5">
                        <p>
                            <a href="http://www.sanjuan.gob.ar" target="_self" title="Gobierno de San Juan">
                                <img src="@(Url.Content("~/EstiloGobierno/img/logorentaswhite.png"))" alt="Gobierno de San Juan" width="100%">
                            </a>
                        </p>
                    </div>
                    <div class="col-6 col-md-3">
                        <h5>Dirección</h5>
                        <ul class="list-unstyled text-small">
                            <li>Av. Libertador Gral. San Martín 750 Oeste - Capital.</li>
                            <li>Centro Cívico, Planta Baja.</li>
                            <li>Conmutador: <a href="tel:2644306500">264 4306500</a></li>
                        </ul>
                    </div>
                    <div class="col-6 col-md-3">
                        <h5>Consultas y servicios</h5>
                        <ul class="list-unstyled text-small">
                            <li><a href="#">Consultas y solicitudes</a></li>
                        </ul>
                    </div>
                    <div class="col-12 col-md-3">
                        <h5>Accesos directos</h5>
                        <ul class="list-unstyled text-small">
                            <li>
                                <a href="https://www.afip.gov.ar" target="_blank"
                                   title="Administración Federal de Ingesos Públicos">AFIP</a>
                            </li>
                            <li>
                                <a href="http://www.comarb.gov.ar" target="_blank"
                                   title="Comisión Arbitral del Convenio Multilateral">Comarb</a>
                            </li>
                            <li>
                                <a href="https://www.dnrpa.gov.ar" target="_blank" title="Dirección Nacional de Registros de la Propiedad
            Automotor">DNRPA</a>
                            </li>
                            <li><a href="https://www.bancosanjuan.com" target="_blank">Banco San Juan</a></li>
                            <li><a href="https://www.pagar.com.ar/" target="_blank">Link Pagos</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>

    </div>

    <partial name="Waiting" />
    <partial name="_Mensaje" />


    <script src="~/js/jquery-3.3.1.min.js"></script>
    <script src="~/js/jquery.validate.js"></script>
    <script src="~/js/jquery.validate-vsdoc.js"></script>
    <script src="~/js/jquery.validate.min.js"></script>
    <script src="~/js/jquery.validate.unobtrusive.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/bootstrap/select2/dist/js/select2.min.js"></script>
    <script src="~/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
    <script src="~/bootstrap-datepicker/locales/bootstrap-datepicker.es.min.js"></script>
    <script src="~/moment/moment.min.js"></script>
    <script src="~/bootstrap/gritter/js/jquery.gritter.min.js"></script>

    <script type="text/javascript">
         var MensajeErrorTempData = '@TempData["error"]';
        var MensajeInfoTempData = '@TempData["info"]';
        var MensajeWarnTempData = '@TempData["warn"]';
        var MensajeSuccessTempData = '@TempData["succ"]';
        var titulo = "";
        var ejecutar = false;
        var mensaje = "";
        if (MensajeErrorTempData !== undefined || MensajeErrorTempData !== "") {
            titulo = "Error";
            ejecutar = true;
            mensaje = MensajeErrorTempData;
        } else if (MensajeInfoTempData !== undefined || MensajeInfoTempData !== "") {
            titulo = "Información";
            ejecutar = true;
            mensaje = MensajeInfoTempData;
        } else if (MensajeWarnTempData !== undefined || MensajeWarnTempData !== "") {
            titulo = "Atención";
            ejecutar = true;
            mensaje = MensajeWarnTempData;
        } else if (MensajeSuccessTempData !== undefined || MensajeSuccessTempData !== "") {
            titulo = "Excelente";
            ejecutar = true;
            mensaje = MensajeSuccessTempData;
        }

        if (ejecutar === true) {
            AbrirMensaje(titulo, mensaje, function (respuesta) {
                $('#msjModal').modal('hide');
            }, false, ["Aceptar"]); //["Aceptar", "Cancelar"]
            return;
        }

    </script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/SATI.BackOffice.Site/Views/Shared/_Mensaje.cshtml
<!-- Modal -->
<div class="modal fade" id="msjModal" tabindex="-1" role="dialog" aria-labelledby="msjTitulo" data-keyboard="false" data-backdrop="static" aria-hidden="true" style="z-index: 999999;" >
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div id="msjHeader" class="modal-header">
                <span id="msjIcono" class="" style="margin-top: -2px; margin-right: 5px;"></span>
                <h5 id="msjTitulo">¡Atención!</h5>
                <button type="button" class="close" onclick="AceptarMensaje('NO');" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div id="msjContenido" class="modal-body">
            </div>
            <div class="modal-footer">
                <button id="btnMensajeAceptar" type="button" class="btn btn-primary">Aceptar</button>
                <button id="btnMensajeCancelar" type="button" class="btn btn-secondary" data-dismiss="modal" onclick="CerrarMensaje('NO');">Cancelar</button>
            </div>
        </div>
    </div>
</div>

<script>
    $("#btnMensajeAceptar").click(function (evento) {
        AceptarMensaje('SI');
        evento.preventDefault();
        evento.stopPropagation();

        return false;
    });

</script>

src/SATI.BackOffice.Site/Views/Shared/_MenuPrincipal.cshtml
<div class="container-fluid" id="menu-ppal-container">
    <hr class="divisor-seccion border-secondary mb-0" aria-hidden="true" />
    <ul class="nav nav-fill row no-gutters" id="myTab" role="tablist">
        <!--nav-tabs-->
        <li class="nav-item col-md-3ths col-xs-3ths pl-0 pr-0">
            <a asp-action="index" asp-controller="Carousel" class="nav-link" title="Gestión de Carrusel">
                <h2 class="">
                    <i class="fas fa-cogs"></i>
                </h2>
                <h6 class="oculta-objeto">
                    Gestión de Carrusel
                </h6>
            </a>
        </li>
        <li class="nav-item col-md-3ths col-xs-3ths pl-0 pr-0">
            <a asp-action="index" asp-controller="NormativaLegal" class="nav-link" title="Normativa Legal">
                <h2 class="">
                    <i class="fas fa-cogs"></i>
                </h2>
                <h6 class="oculta-objeto">
                    Normativa Legal
                </h6>
            </a>
        </li>

        <li class="nav-item col-md-3ths col-xs-3ths pl-0 pr-0">
            <a asp-action="index" asp-controller="IndisponibilidadSitio" class="nav-link" title="Indisponibilidad del Sitio">
                <h2 class="">
                    <i class="fas fa-cogs"></i>
                </h2>
                <h6 class="oculta-objeto">
                    Indisponibilidad del Sitio
                </h6>
            </a>
        </li>
        
    </ul>
    <hr class="divisor-seccion border-secondary mt-0 mb-0" aria-hidden="true" />
</div>

src/SATI.BackOffice.Site/Views/Shared/_TituloSimple.cshtml
@*<div class="card">
    <div class="card-header p-1 bg-danger text-white">
        <span class="float-left p-2 ">
            <i class="fas fa-object-group"></i>
            <strong> @ViewData["Title"]</strong>
        </span>
        <a class="float-right p-2 btn btn-link" style="color: white;" href="@(Url.Content("~/"))">
            <i class="fas fa-undo"></i>
        </a>
    </div>
    <div class="col-md-12 m-0 p-0">

    </div>
</div>*@

<div class="container">
    <h2 class="text-center text-secondary"> @ViewData["Title"]</h2>
</div>